spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/avalon?currentSchema=public&sslmode=disable
oauth2:
  ignore-urls:
    - /actuator/**
  jwt-private-key-location: classpath:/rsa/private_key.pem
  jwt-public-key-location: classpath:/rsa/public_key.pem