spring:
  application:
    name: avalon-admin
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-format: "\"%s\""